language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
notifications:
  email: false
before_install:
  # - sudo apt-get update
  # - sudo apt-get install maven
env:
  - DB=mysql
#  - DB=postgresql
before_script:
  #  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database strano_test'
  # - psql -l -U postgres
script:
  # - mysql -e 'show databases'
  # - psql -c 'show databases' -U postgres
  - mvn package
  - mvn dependency:get -Dartifact=mysql:mysql-connector-java:5.1.18
  - cp $HOME/.m2/repository/mysql/mysql-connector-java/5.1.18/mysql-connector-java-5.1.18.jar $TRAVIS_BUILD_DIR/target
  - ls $TRAVIS_BUILD_DIR/target
  - java -Djava.ext.dirs=$TRAVIS_BUILD_DIR/target sqlline.SqlLine -d com.mysql.jdbc.Driver -u jdbc:mysql://0.0.0.0:3306 -f test.sql
