language: python
python:
  - "2.7"
cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get install sqlline
env:
  - DB=mysql
  - DB=postgresql
script:
  - mysql -e 'show databases'
  - psql -c 'show databases' -U postgres
before_script:
#  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database strano_test'
  - psql -c 'create database strano_test' -U postgres
